name: CI
# workflow level envs
env:
  PIPE: cicd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
# job level envs
  checkout:
    env:
      STAGE: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  process:
    runs-on: ubuntu-latest
    # step level envs
    steps:
      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo Hello, World!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
