name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t uzairr91/uzairr uzairr91/uzairr:tagname
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push uzairr/docker-ci-proj:latest
    - run: docker push uzairr91/uzairr:latest
