name: Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
      branches: [ "master" ]

jobs:
    build:

      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.9.21, 3.10.16, 3.13.1]

      steps:
        - uses: actions/checkout@v2
        - name: Use Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: "Installing Dependencies"
          run: pip install -r requirements.txt

    unit-tests:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          python-version: [3.9.21, 3.10.16, 3.13.1]

      steps:
        - uses: actions/checkout@v2
        - name: Use Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: "Installing Dependencies"
          run: pip install -r requirements.txt

        - name: "Running test cases"
          run: python manage.py test
